In [5]:
import pandas as pd
import numpy as np

In [17]:
url_red = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
url_white = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"

df_red = pd.read_csv(url_red, sep=';')
df_white = pd.read_csv(url_white, sep=';')

In [18]:
df_red.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [22]:
df_red["type"] = "red"
df_white["type"] = "white"

In [23]:
df = pd.concat([df_red, df_white], ignore_index=True)

In [24]:
df.shape

(6497, 13)

In [25]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [ ]:
# cek tipe data and jumlah baris non-null setiap kolom
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
 12  type                  6497 non-null   str
dtypes: float64(11), int64(1), str(1)
memory usage: 660.0 KB

In [ ]:
# cek jumlah data missing value di setiap kolom
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
type                    0
dtype: int64

In [30]:
df.duplicated()

0       False
1       False
2       False
3       False
4        True
        ...
6492    False
6493    False
6494    False
6495    False
6496    False
Length: 6497, dtype: bool

In [31]:
print("Jumlah duplikat: ", df.duplicated().sum())

Jumlah duplikat:  1177

In [32]:
# Statistik deskriptif & cek skewness/outlier
df.describe(percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99])

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000,6497.000000
mean,7.215307,0.339666,0.318633,5.443235,0.056034,30.525319,115.744574,0.994697,3.218501,0.531268,10.491801,5.818378
std,1.296434,0.164636,0.145318,4.757804,0.035034,17.749400,56.521855,0.002999,0.160787,0.148806,1.192712,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
1%,5.100000,0.120000,0.000000,0.900000,0.021000,4.000000,11.000000,0.988920,2.890000,0.300000,8.700000,4.000000
5%,5.700000,0.160000,0.050000,1.200000,0.028000,6.000000,19.000000,0.989900,2.970000,0.350000,9.000000,5.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
95%,9.800000,0.670000,0.560000,15.000000,0.102000,61.000000,206.000000,0.999392,3.500000,0.790000,12.700000,7.000000
99%,12.000000,0.880000,0.740000,18.200000,0.186160,77.000000,238.000000,1.000600,3.640000,0.990000,13.400000,8.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

In [ ]:
# Perbandingan Mean vs Median untuk melihat skewness fitur numerik

numeric_cols = df.select_dtypes(include="number").columns
comparison = pd.DataFrame({
    "mean": df[numeric_cols].mean(),
    "median": df[numeric_cols].median(),
    "std": df[numeric_cols].std(),
    "min": df[numeric_cols].min(),
    "max": df[numeric_cols].max()
})
comparison

                            mean     median        std      min        max
fixed acidity           7.215307    7.00000   1.296434  3.80000   15.90000
volatile acidity        0.339666    0.29000   0.164636  0.08000    1.58000
citric acid             0.318633    0.31000   0.145318  0.00000    1.66000
residual sugar          5.443235    3.00000   4.757804  0.60000   65.80000
chlorides               0.056034    0.04700   0.035034  0.00900    0.61100
free sulfur dioxide    30.525319   29.00000  17.749400  1.00000  289.00000
total sulfur dioxide  115.744574  118.00000  56.521855  6.00000  440.00000
density                 0.994697    0.99489   0.002999  0.98711    1.03898
pH                      3.218501    3.21000   0.160787  2.72000    4.01000
sulphates               0.531268    0.51000   0.148806  0.22000    2.00000
alcohol                10.491801   10.30000   1.192712  8.00000   14.90000
quality                 5.818378    6.00000   0.873255  3.00000    9.00000

In [34]:
# menghapus baris yang duplikat
df_clean = df.drop_duplicates().copy()

In [38]:
print("Jumlah baris awal(sebelum hapus baris duplikat) :", len(df))
print("Jumlah baris sekarang: ", len(df_clean))
print("Total baris terbuang: ", len(df) - len(df_clean))
print("Sisa duplikat: ", df_clean.duplicated().sum())

df_clean.head()

Jumlah baris awal(sebelum hapus baris duplikat) : 6497
Jumlah baris sekarang:  5320
Total baris terbuang:  1177
Sisa duplikat:  0

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5,red

In [39]:
# Pemisahan Fitur (X) dan Target (y)
X = df_clean.drop(columns=["quality"])
y = df_clean["quality"]

print("Ukuran Fitur (X):", X.shape)
print("Ukuran Target (y):", y.shape)

Ukuran Fitur (X): (5320, 12)
Ukuran Target (y): (5320,)

In [41]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\thear\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.5.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.25.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.3 MB 6.5 MB/s eta 0:00:02
   ------------ --------------------------- 2.6/8.3 MB 7.2 MB/s eta 0:00:01
   ---------------------- ----------------- 4.7/8.3 MB 8.1 MB/s eta 0:00:01
   --------------------------- ------------ 5.8/8.3 MB 7.6 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.3 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 7.2 MB/s  0:00:01
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading narwhals-2.25.0-py3-none-any.whl (467 kB)
Downloading scipy-1.18.1-cp314-cp314-win_amd64.whl (37.4 MB)
   ---------------------------------------- 0.0/37.4 MB ? eta -:--:--
   - -------------------------------------- 1.0/37.4 MB 5.4 MB/s eta 0:00:07
   - -------------------------------------- 1.3/37.4 MB 5.3 MB/s eta 0:00:07
   -- ------------------------------------- 2.4/37.4 MB 4.0 MB/s eta 0:00:09
   --- ------------------------------------ 3.1/37.4 MB 4.1 MB/s eta 0:00:09
   ---- ----------------------------------- 3.9/37.4 MB 4.1 MB/s eta 0:00:09
   ----- ---------------------------------- 4.7/37.4 MB 4.0 MB/s eta 0:00:09
   ----- ---------------------------------- 5.5/37.4 MB 3.8 MB/s eta 0:00:09
   ------ --------------------------------- 6.3/37.4 MB 3.9 MB/s eta 0:00:08
   ------- -------------------------------- 7.1/37.4 MB 3.9 MB/s eta 0:00:08
   -------- ------------------------------- 8.1/37.4 MB 3.9 MB/s eta 0:00:08
   --------- ------------------------------ 8.7/37.4 MB 3.9 MB/s eta 0:00:08
   ---------- ----------------------------- 9.7/37.4 MB 3.9 MB/s eta 0:00:08
   ----------- ---------------------------- 10.5/37.4 MB 4.0 MB/s eta 0:00:07
   ------------ --------------------------- 11.3/37.4 MB 3.9 MB/s eta 0:00:07
   ------------ --------------------------- 12.1/37.4 MB 4.0 MB/s eta 0:00:07
   ------------- -------------------------- 12.8/37.4 MB 3.9 MB/s eta 0:00:07
   -------------- ------------------------- 13.9/37.4 MB 3.9 MB/s eta 0:00:06
   --------------- ------------------------ 14.9/37.4 MB 4.0 MB/s eta 0:00:06
   ---------------- ----------------------- 15.5/37.4 MB 3.9 MB/s eta 0:00:06
   ----------------- ---------------------- 16.3/37.4 MB 3.9 MB/s eta 0:00:06
   ----------------- ---------------------- 16.8/37.4 MB 3.9 MB/s eta 0:00:06
   ------------------ --------------------- 17.3/37.4 MB 3.8 MB/s eta 0:00:06
   ------------------- -------------------- 17.8/37.4 MB 3.8 MB/s eta 0:00:06
   ------------------- -------------------- 18.6/37.4 MB 3.7 MB/s eta 0:00:06
   -------------------- ------------------- 19.1/37.4 MB 3.7 MB/s eta 0:00:05
   --------------------- ------------------ 20.2/37.4 MB 3.7 MB/s eta 0:00:05
   ---------------------- ----------------- 21.0/37.4 MB 3.7 MB/s eta 0:00:05
   ----------------------- ---------------- 21.5/37.4 MB 3.7 MB/s eta 0:00:05
   ----------------------- ---------------- 22.3/37.4 MB 3.7 MB/s eta 0:00:05
   ------------------------ --------------- 23.3/37.4 MB 3.7 MB/s eta 0:00:04
   -------------------------- ------------- 24.4/37.4 MB 3.8 MB/s eta 0:00:04
   --------------------------- ------------ 25.4/37.4 MB 3.8 MB/s eta 0:00:04
   ---------------------------- ----------- 26.5/37.4 MB 3.9 MB/s eta 0:00:03
   ----------------------------- ---------- 27.5/37.4 MB 3.9 MB/s eta 0:00:03
   ------------------------------ --------- 28.8/37.4 MB 4.0 MB/s eta 0:00:03
   -------------------------------- ------- 30.4/37.4 MB 4.0 MB/s eta 0:00:02
   --------------------------------- ------ 31.5/37.4 MB 4.1 MB/s eta 0:00:02
   ---------------------------------- ----- 32.2/37.4 MB 4.1 MB/s eta 0:00:02
   ----------------------------------- ---- 33.3/37.4 MB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 34.1/37.4 MB 4.1 MB/s eta 0:00:01
   ------------------------------------- -- 34.9/37.4 MB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 35.9/37.4 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  36.7/37.4 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.4 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------- 37.4/37.4 MB 4.1 MB/s  0:00:09
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, scikit-learn

   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------ --------------------------------- 1/6 [scipy]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   -------------------- ------------------- 3/6 [cloudpickle]
   -------------------------- ------------- 4/6 [joblib]
   -------------------------- ------------- 4/6 [joblib]
   -------------------------- ------------- 4/6 [joblib]
   -------------------------- ------------- 4/6 [joblib]
   -------------------------- ------------- 4/6 [joblib]
   -------------------------- ------------- 4/6 [joblib]
   -------------------------- ------------- 4/6 [joblib]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   --------------------------------- ------ 5/6 [scikit-learn]
   ---------------------------------------- 6/6 [scikit-learn]

Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.25.0 scikit-learn-1.9.0 scipy-1.18.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [44]:
from sklearn.model_selection import train_test_split

# membagi data yang mana 80& untuk Training Set, 20% untuk Testing Set
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=X["type"]
)

print("Ukuran X_train (Data Latihan): ", X_train.shape)
print("Ukuran X_test (Data Ujian): ", X_test.shape)
print("Ukuran y_train: ", y_train.shape)
print("Ukuran y_test: ", y_test.shape)

Ukuran X_train (Data Latihan):  (4256, 12)
Ukuran X_test (Data Ujian):  (1064, 12)
Ukuran y_train:  (4256,)
Ukuran y_test:  (1064,)

In [47]:
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
4491,6.7,0.42,0.46,9.7,0.054,67.0,234.0,0.99848,3.23,0.50,9.0,white
3267,7.9,0.18,0.33,1.2,0.033,20.0,72.0,0.99220,3.12,0.38,10.5,white
4433,6.2,0.15,0.27,1.4,0.041,51.0,117.0,0.99090,3.28,0.38,11.2,white
2619,8.6,0.20,0.42,1.5,0.041,35.0,125.0,0.99250,3.11,0.49,11.4,white
38,5.7,1.13,0.09,1.5,0.172,7.0,19.0,0.99400,3.50,0.48,9.8,red
...,...,...,...,...,...,...,...,...,...,...,...,...
4388,6.9,0.40,0.43,6.2,0.065,42.0,178.0,0.99552,3.11,0.53,9.4,white
5127,6.9,0.75,0.13,6.3,0.036,19.0,50.0,0.99312,3.09,0.25,11.1,white
1382,8.0,0.60,0.22,2.1,0.080,25.0,105.0,0.99613,3.30,0.49,9.9,red
1669,6.2,0.27,0.43,7.8,0.056,48.0,244.0,0.99560,3.10,0.51,9.0,white
2613,6.1,0.16,0.27,12.6,0.064,63.0,162.0,0.99940,3.66,0.43,8.9,white

In [48]:
# pisahin nama kolom numerik dan kategorikal di X_train

num_cols = X_train.select_dtypes(include="number").columns.tolist()
cat_cols = X_train.select_dtypes(include="object").columns.tolist()

print("Kolom Numerik: ", num_cols)
print("Kolom Kategorikal; ", cat_cols)

Kolom Numerik:  ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']
Kolom Kategorikal;  ['type']

C:\Users\thear\AppData\Local\Temp\ipykernel_368\486471344.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X_train.select_dtypes(include="object").columns.tolist()